### ISSUE TITLE
spike: dependency injection use

### ISSUE THREAD

**Issue by dantasrafael** [colibri-project-io/colibri-sdk-go#13]
Libraries for working with dependency injection.

[alice](https://github.com/magic003/alice) - Aditive dependency injection container for Golang.
[di](https://github.com/goava/di) - A dependency injection container for go programming language.
[dig](https://github.com/uber-go/dig) - A reflection based dependency injection toolkit for Go.
[dingo](https://github.com/i-love-flamingo/dingo) - A dependency injection toolkit for Go, based on Guice.
[do](https://github.com/samber/do) - A dependency injection framework based on Generics.
[fx](https://github.com/uber-go/fx) - A dependency injection based application framework for Go (built on top of dig).
[gocontainer](https://github.com/vardius/gocontainer) - Simple Dependency Injection Container.
[goioc/di](https://github.com/goioc/di) - Spring-inspired Dependency Injection Container.
[GoLobby/Container](https://github.com/golobby/container) - GoLobby Container is a lightweight yet powerful IoC dependency injection container for the Go programming language.
[google/wire](https://github.com/google/wire) - Automated Initialization in Go.
[HnH/di](https://github.com/HnH/di) - DI container library that is focused on clean API and flexibility.
[kinit](https://github.com/go-kata/kinit) - Customizable dependency injection container with the global mode, cascade initialization and panic-safe finalization.
[linker](https://github.com/logrange/linker) - A reflection based dependency injection and inversion of control library with components lifecycle support.
[nject](https://github.com/muir/nject) - A type safe, reflective framework for libraries, tests, http endpoints, and service startup.
[wire](https://github.com/Fs02/wire) - Strict Runtime Dependency Injection for Golang.

**Comment by sebastiaofortes** [comment]
@dantasrafael It would be a good option to perform automatic dependency injection using reflection. Would you create your own injection container instead of using a third-party framework.

**Comment by sebastiaofortes** [comment]
@dantasrafael I have an example of an automatic dependency injection container in this repository: https://github.com/sebastiaofortes/gonnect
